- app/auth/index.js
- app/auth/local.js
- app/controllers/account.js
This replaces pull request #129.
I took @geoffwhittington's code and moved it to the auth layer - so it works for both web and xmpp, and is compatible with all account types.
> Added account lockout.

- app.js
I haven't been able to test this but it looks like what we need
> set secure flag on cookies when using https

- app.js
- package.json
Added some middleware to mitigate:
* TLS/SSL Stripping
* External framing
* Probing for vulnerable software
* Attacks based on MIME-type confusion.
> Put on a security helmet

- media/js/util/message.js
I mean, this is probably okay. Right??
> Fix link parsing

- media/css/style.css
- media/js/views/room.js
- media/less/style/chat/rooms.less
- templates/includes/js-templates.html
> Enable profile tap on touch devices

- app.js
- app/controllers/files.js
- app/controllers/messages.js
- app/core/files.js
- app/core/files/local.js
- app/core/files/s3.js
- app/core/index.js
- app/core/messages.js
- app/models/file.js
- defaults.yml
- package.json
- settings.yml.sample
I've implemented backend support for local file and S3 uploading.
I've tested the local file hosting, but have not tested S3 support. The S3 code is essentially the same as it was in 0.2.
I'll leave the frontend code for you to do @hhaidar.
Whether you want to merge this in and do the frontend in a separate pull request, or do it all in this pull request - that's up to you :smile:
> File support

- Vagrantfile
Fixes #200 by removing the dollar sign.
> Fixed typo which causes vagrant not to run

- .gitignore
- media/js/views/transcript.js
- templates/transcript.html
Improves the date picking functionality on the transcript page.
> Improve transcript datepicker

- app/models/user.js
We have dots in our usernames.  We need the dots.
> Allow dot in username

- app/models/user.js
Reverts sdelements/lets-chat#236
> Revert "Allow dot in username"

- app/xmpp/msg-processors/room-join.js
Follow xmpp spec http://xmpp.org/extensions/xep-0045.html#createroom
> Create room if user join unknown room

- media/js/client.js
hey hope this does what you where after, if not id happily take another shot at it :) ive attached an image of the error that is shown also
> issue #229 Room creation with invalid slug doesnt error out.

- app/core/files/s3.js
> Fix S3 uploads

- app.js
- defaults.yml
- settings.yml.sample
> Add a host setting

- app/controllers/misc.js
- app/misc/robots.txt
- defaults.yml
> Add robots.txt

- app.js
- app/config.js
Hi,
I use lets chat on OpenShift.
Since there is already compatibility with Heroku, you might be interested in this.
> Add compatibility with openshift for hosting

- templates/chat.html
Add fa-fw class to the user dropdown on the top-left. I think this looks slightly better :)
> Use fixed-width FontAwesome icons for the user menu.

- app/controllers/account.js
- templates/login.html
Prompt users to confirm their password when self-registering.
Fixes #184
> Prompt users to confirm their password when self-registering.

- Vagrantfile
> Start the server on all network interfaces

- media/less/style/chat/browser.less
- media/less/style/chat/rooms.less
- templates/includes/js/browser-item.html
> Clip long room names

- app/controllers/connections.js
- app/controllers/usermessages.js
- app/controllers/users.js
- app/core/account.js
- app/core/index.js
- app/core/presence.js
- app/core/presence/connection-collection.js
- app/core/presence/room-collection.js
- app/core/presence/room.js
- app/core/presence/user-collection.js
- app/core/usermessages.js
- app/core/users.js
- app/models/usermessage.js
- app/xmpp/events/user-avatar-ready.js
- app/xmpp/events/user-connect.js
- app/xmpp/events/user-disconnect.js
- app/xmpp/events/user-join.js
- app/xmpp/events/usermessage-created.js
- app/xmpp/helper.js
- app/xmpp/index.js
- app/xmpp/msg-processors/room-join.js
- app/xmpp/msg-processors/root-join.js
- app/xmpp/msg-processors/roster-get.js
- app/xmpp/msg-processors/user-message.js
- app/xmpp/msg-processors/vcard-get.js
- defaults.yml
Implemented for both API and XMPP.
When logged into XMPP, you'll see other users in your friend list - but only those connected via XMPP (until we implement the web interface).
Web client does not currently support this functionality.
#282
> Private 1-to-1 chat

- media/js/views/room.js
> Remove current user from autocomplete

- media/js/views/room.js
Add support for inplace insert NewLine by Shift+Enter.
> Add support NewLine by shift+Enter

- media/less/style/chat/messages.less
- media/less/style/chat/rooms.less
- templates/includes/js/room.html
sometimes I cry myself to sleep
> Fix chrome 43 layout issues

- media/less/style/chat/client.less
- media/less/style/chat/tabs.less
- templates/chat.html
> Scroll when multiple tabs are there

- app/controllers/files.js
- app/controllers/messages.js
- app/controllers/rooms.js
- app/core/files.js
- app/core/messages.js
- app/core/rooms.js
- app/models/file.js
- app/models/message.js
- app/models/room.js
- app/xmpp/msg-processors/room-join.js
- defaults.yml
- media/js/client.js
- media/js/views/browser.js
- media/js/views/room.js
- media/less/style/chat/rooms.less
- templates/includes/js/room.html
- templates/includes/modals/add-room.html
The user can make a new room private by checking the private checkbox.
Once a private room has been created, the participants field can be edited using the Edit Room form.
This pull request supercedes #413 and #438.
> Private rooms - participants list is editable

- Dockerfile
see: https://docs.docker.com/userguide/dockervolumes/
> Make `uploads` a Docker volume

- Dockerfile
This removes unnecessary bloat from the final image.
> Merge `apt-get` steps in Dockerfile

- defaults.yml
- media/js/chat.js
- media/js/views/modals.js
- media/js/views/window.js
- templates/includes/js/room.html
- templates/includes/modals/giphy.html
> Giphy is fully configurable

- app/controllers/account.js
- media/less/style/chat/client.less
- templates/chat.html
Displays the version from package.json in the UI. Where should I put the information in the UI? Any ideas?
Related to #546.
> Display version in ui

- locales/ru.json
http://new.gramota.ru/spravka/buro/search-answer?s=255872
> Follow the russian language rules.

- .travis.yml
- app/xmpp/events/message-created.js
- app/xmpp/events/room-archived.js
- app/xmpp/events/room-updated.js
- app/xmpp/events/user-avatar-ready.js
- app/xmpp/events/user-connect.js
- app/xmpp/events/user-disconnect.js
- app/xmpp/events/user-join.js
- app/xmpp/events/user-leave.js
- app/xmpp/events/usermessage-created.js
- app/xmpp/index.js
- app/xmpp/msg-processor.js
- app/xmpp/msg-processors/room-join.js
- package.json
* node-xmpp-core is not needed (and possibly harmful as you possibly could be using a different version as node-xmpp-server)
* node-xmpp-server received several important fixes
* node-xmpp-server now installs on Node.js 4
> Update node-xmpp-server & Node.js 4

- locales/fr.json
> Add lacking new placeholder from #667

- locales/ja.json
> fix japanese translation

- docker/Dockerfile
> Add builtAssets to docker setup

- media/js/util/message.js
older code eats the last subdirectory in url.
> Fix the uploaded file's path error
