Dockerfile, README.md, Vagrantfile
README drops references to a specific branch. VagrantFile can take a parameter via environment variable to set the branch to checkout. I wasn't sure how to parameterize the Dockerfile, so that just clones master for the time being.
=> Drop references to release/0.3.0.

Dockerfile
Having Docker check out from `master` means if you make any local changes, you can't test them locally in Docker. Using a [mounted `VOLUME`](https://docs.docker.com/reference/builder/#volume) means you can do local development through Docker.
The [Docker wiki instructions](https://github.com/sdelements/lets-chat/wiki/Docker) will have to be updated to include [`--volume`/`-v`](https://docs.docker.com/reference/commandline/cli/):
```
docker run -p 5000:5000 -v .:/lets-chat --link db:db lets-chat
```
=> Use mounted volume rather than checking out from GitHub's master

fig.yml
[Fig](http://fig.sh) is a wrapper for Docker, which allows easy maintenance of multiple Docker containers. It will become what was [announced as Docker Compose](http://blog.docker.com/2015/01/dockercon-eu-introducing-docker-compose/).
This pull request adds a `fig.yml` file which leverages [Let's Chat's `Dockerfile`](https://github.com/sdelements/lets-chat/blob/master/Dockerfile) (as [documented in the wiki](https://github.com/sdelements/lets-chat/wiki/Docker)) and makes running Let's Chat as easy as:
``` bash
fig up
```
Once merged, a Fig section should be [added to the Docker section of the wiki](https://github.com/sdelements/lets-chat/wiki/Docker) so that people have the option to either use Docker directly, or simply use Fig.
=> Add Fig support (for Docker)

Dockerfile
This change makes use of the offical node-onbuild container, no need make a custom node/npm installation.
=> Use official node-container

_layouts/index.html
Hey, I don't know if I missed something, but the instructions didn't seem to tell how to run the app. I figured it was `npm start` looking at `package.json`, but it's not on the home page. So I hope this pullrequest improves things! Aweomse project :)
=> Add instructions to start Let's Chat

README.md
I added a link to my Azure storage plugin to your README file.
I wasn't sure where the best place would be to place that link, so I added it to the list of available file uploads. Alternatively we could create an 3rd party section for all plugins which were not developed by you or something like that ...
=> Added link to azure storage plugin

app/controllers/files.js
New uploads were always posted in the room, regardless of the flag "Post to room" was set or not.
The result of  ``` req.param('post') ``` is a string which caused the comparsion to return always true.
=> Flag Post to room didn't work

app.js
I'm running lets-chat by a custom init script and it's a bit of a problem that the process is called `app` for purpose of `ps`, `pidof` and relatives. This patch changes the process title to a unique `letschat`. I opted to not include a space or dash in the name for compatibility.
=> Add process title

media/js/util/message.js
When formatting URLs to links in messages, unicode characters are now
accepted.
URLs like http://www.åäöü.fi/ work with the patch.
=> Allow unicode characters in URL

bower.json, media/js/vendor.js, media/js/vendor/favico.js/favico.js, media/js/views/window.js
The same way as the document title for an inactive window is updated
to show new messages and mentions, favicon is changed to show new
mentions only.
I find the behavior extremely useful when the chat window is behind a pinned tab. So, the feature itself would be great to have even if you prefer some other solution. [Favico.js](http://lab.ejci.net/favico.js/) is the library used here.
=> Show unread mentions as favicon badge

_layouts/index.html
This commit adds a "Try a demo" button to the front page, which links to:
https://demo.sandstorm.io/appdemo/qkgkaxfqhgsff8zgx2f4nf1a8xvmpte6wa19egmfkk06mzt7e8dh
This is backed by @jparyani's package of Let's Chat for Sandstorm. (Sandstorm is an open source project that makes it easy to run web applications with a click.)
More info on these app demo buttons here: https://blog.sandstorm.io/news/2015-02-06-app-demo.html
I hope you'll consider this pull request, and merge it if you like!
=> Add a "Try a demo" button

media/js/util/message.js
This causes lots of irritation especially when pasting Ruby snippets. Ruby symbols are replaced by an emote too often. Is there a particular reason for not doing this?
=> Require closing colon for emotes

Dockerfile
Even though running root inside a container is more secure than running root outside a container it is not necessary. Lets-Chat works just fine with a user that has got reduced privileges. I am running this `Dockerfile` in production.
=> Drop root privileges in Dockerfile

app/models/user.js, defaults.yml, settings.yml.sample
The bcrypt module gives an error if it encounters a legacy password hash.
I just took out those checks and placed them before bcrypt happens.
=> Fix broken legacy passwords

media/js/views/room.js
When you scroll up to see older messages and then reply to one of them, you probably want to see the message you just typed instead of getting no response whatsoever. At least I do. :)
=> Scroll down after own message

app/core/avatar-cache.js
I'm trying to run Lets chat inside corporate network behind proxy.
Application crashes when Avatar caching is called. Problem is that there is no error handler for HTTP request. The error handler ignores the error as the calls to cache handle the situation where Cache does not contain user Avatar.
Ideally, it should be possible to setup HTTP Proxy for the HTTP calls to the external services. This pull request only fixes the very immediate problem of Crashing Application.
There should be a way to use http.get function with proxy.
=> Handling error on Avatar caching. Ignoring Exception

media/js/util/message.js, media/less/style/chat/messages.less
I created this branch mainly to test that my dev environment for Let's Chat is set up correctly but I think it's still useful.
In current `master`, mentions in messages are just transformed into something like `<strong>@dfyx</strong>`. My branch changes this to generate `<span class="lcb-message-mention">@dfyx</span>`. The CSS to make it look the same as before is included.
As said, it was initially more of an experiment. But in general I think it makes it easier to add styles and maybe scripts (like a tooltip) to mentions.
=> Better markup for mentions

package.json
It's easier to use "npm stop" command to stop Let's Chat, especially when you want to make it a service for your server.
=> Add stop command in package.json for npm stop

media/js/views/window.js
It now uses the `document.title` property to change the title. My users reported that the title stopped updating as of the last update of Google Chrome. Using `document.title` is the canonical way and seems to fix their issue.
=> Fix changing the browser title

README.md
Hey,
Thanks for this awesome chat app.
This PR adds Cloudron as a deployment option for Let's Chat. It relies on wiki changes (not sure how to make a PR for that). https://github.com/cloudron-io/lets-chat/wiki/Cloudron is the text for the Cloudron page. 
It will be great if you can have us listed!
The source code of the app is at https://github.com/cloudron-io/letschat-app.
=> Add cloudron letschat app to README.md

migroose.js
`migrations.slice(migrations.length - 1)[0]`
we should not do this when `migrations.length === 0`
=> donot check migration when migrations.length is 0

app/core/presence/connection.js, package.json
Hi there,
This week a new version of the [uuid](https://github.com/kelektiv/node-uuid) module got released. The old module which was available by the name [node-uuid](https://www.npmjs.com/package/node-uuid) got deprecated and will show error message upon every install of the module.
To get rid of those install errors I've created this **automated pull request**. I've run some checks against your code base to test whether you're using one of the [deprecated apis](https://github.com/kelektiv/node-uuid/commit/5ae7287fc935eb55ef39133e4be17ef623ca000e), but this isn't the case.
Please test the changes against your code. I didn't run any tests and therefore can't guarantee that it isn't breaking. You can also just close this pr if you don't want to update your module.
In case there's already …
=> Update uuid to version 3.0.0
